# .github/workflows/build.yml

name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build / Linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build VFSMOD
        uses: ./.github/actions/build-vfsmod
        with:
          gfortran: 13

      - name: Set archive name
        run: echo "ARCHIVE=vfsmod-$(cat VERSION)-linux.tar.gz" >> "$GITHUB_ENV"

      - name: Package
        run: tar -czf "${{ env.ARCHIVE }}" -C build vfsm uh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: vfsmod-linux.tar.gz
          path: ${{ env.ARCHIVE }}
          retention-days: 3

  build-macos:
    name: Build / macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Build VFSMOD
        uses: ./.github/actions/build-vfsmod
        with:
          gfortran: 13

      - name: Set archive name
        run: echo "ARCHIVE=vfsmod-$(cat VERSION)-macos.tar.gz" >> "$GITHUB_ENV"

      - name: Package
        run: tar -czf "${{ env.ARCHIVE }}" -C build vfsm uh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: vfsmod-macos.tar.gz
          path: ${{ env.ARCHIVE }}
          retention-days: 3

  build-windows:
    name: Build / Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build VFSMOD
        uses: ./.github/actions/build-vfsmod
        with:
          gfortran: 13

      - name: Set archive name
        shell: pwsh
        run: |
          "ARCHIVE=vfsmod-$(Get-Content VERSION)-windows.zip" >> $env:GITHUB_ENV

      - name: Package
        shell: pwsh
        run: Compress-Archive -Path .\build\vfsm.exe, .\build\uh.exe -DestinationPath $env:ARCHIVE

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: vfsmod-windows.zip
          path: ${{ env.ARCHIVE }}
          retention-days: 3